[project]
name = "mlops-hw01"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "mlflow>=3.6.0",
    "pydantic-settings>=2.12.0",
    "ruamel-yaml>=0.18.16",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
]
